# Generated by Django 4.0.1 on 2022-01-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountNumber', models.CharField(max_length=250, null=True)),
                ('Description', models.TextField(null=True)),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Industry', models.CharField(max_length=250, null=True)),
                ('OwnerId', models.CharField(max_length=250, null=True)),
                ('Ownership', models.CharField(max_length=250, null=True)),
                ('Website', models.URLField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=250)),
                ('CreatedDate', models.DateTimeField()),
                ('Email', models.CharField(max_length=100, null=True)),
                ('FirstName', models.CharField(max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50, null=True)),
                ('ProfileId', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
